---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    resource_group_vm: nabilresources
    vnet_name: nabilvnet
    subnet_name: nabilsubnet
    vm_name: ansible-VM
    location: westeurope
    admin_username: ansibleuser
    admin_password: Password@123
    repo_url: https://github.com/yungezz/helloworld.git
    workspace: ~/src/helloworld

  tasks:

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: nabilresources
        allocation_method: Static
        name: pip-ansible
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"


    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2 
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        #ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/ansibleuser/.ssh/authorized_keys
            key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHyecrKtacZ6SIu57YSMsqSmxYXfWqPhgJfoGORRFrkz9VyAdDDxhRhx4r7pJgX4DhfHDp8UoL20jxLsm8VinmRs5Ex63k3widgwP34E6o4WSnrBS2LNNNEsTGcdnfbWzUBubmtT1dqSjjN2CtGr/QYM0qlPCZnQwaQpyn3jqkapANAjggB+5B0wK5MeowixsPrZgNItNkE3FNJLLXh1XK+oVsZeXigxZWiVbxZg93qGQ0ppf/JF+/MW9bx+xscW9O9T/W8ALNbji+432ldHhEjSciKYtpX8L5OQtX9uNykTuHQQ2IPRiDWg6qPmVsFY/DxpsGvTnSfWEPvJw2qrdZ nabilelkhalii@nabilelkhalii-VirtualBox"
        virtual_network_name: "{{ vnet_name }}"
        subnet_name: "{{ subnet_name }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
        tags:
          asset_owner : "julien.seveau@cgi.com"
          asset_project_desc : "test"
          asset_project_end : "12-21"
          autostart : "no"
          autoshutdown : "no"
      register: output

    - debug:
        msg: username {{ admin_username }} has Password {{ admin_password }}

    - name: add azure vm into host
      add_host:
        name: ansible-VM
        ansible_host: '{{ output.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'
        ansible_user: "{{ admin_username }}"
        ansible_host_key_checking: true 
   
    - name: wait for the WinRM port to come online
      wait_for:
        port: 22
        host: '{{ output.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'
        timeout: 600

    - debug:
        msg: ip - '{{ output.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'

    - name: execute command
      shell: touch testest /home/{{ admin_username }}