---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    resource_group_vm: nabiliqresources
    vnet_name: vnetiq
    subnet_name: subnet-ansibleVM
    vm_name: ansible-VM
    location: westeurope
    admin_username: ansibleuser
    admin_password: Password@123

  tasks:

    - name: Create an Ansible Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vnet_name }}"
        address_prefixes_cidr:
            - "10.1.0.0/16"
            - "172.100.0.0/16"
        dns_servers:
            - "127.0.0.1"
            - "127.0.0.2"
        tags:
            testing: testing
            delete: on-exit

    - name: Create an Ansible Subnet Network
      azure_rm_subnet:
        resource_group: "{{ resource_group_vm }}"
        virtual_network_name: "{{ vnet_name }}"
        name: "{{ subnet_name }}"
        address_prefix_cidr: "10.1.0.0/24"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vm_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: Tomcat
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        virtual_network_name: "{{ vnet_name }}"
        subnet_name: "{{ subnet_name }}"
        public_ip_allocation_method: Disabled
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
      register: output
