- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    resource_group_vm: nabilresources
    vnet_name: nabilvnet
    subnet_name: nabilsubnet
    vm_name: ansible-vm
    location: westeurope
    repo_url: https://github.com/yungezz/helloworld.git
    workspace: ~/src/helloworld
    admin_username: nabiluser
    admin_password: Password@123
#  roles:
#    - azure.azure_preview_modules
  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: nabilresources
        allocation_method: Static
        name: pip-ansible
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vm_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            direction: Inbound
          - name: Tomcat
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        ssh_public_keys:
          - path: /home/ansibleuser/.ssh/authorized_keys
            key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHyecrKtacZ6SIu57YSMsqSmxYXfWqPhgJfoGORRFrkz9VyAdDDxhRhx4r7pJgX4DhfHDp8UoL20jxLsm8VinmRs5Ex63k3widgwP34E6o4WSnrBS2LNNNEsTGcdnfbWzUBubmtT1dqSjjN2CtGr/QYM0qlPCZnQwaQpyn3jqkapANAjggB+5B0wK5MeowixsPrZgNItNkE3FNJLLXh1XK+oVsZeXigxZWiVbxZg93qGQ0ppf/JF+/MW9bx+xscW9O9T/W8ALNbji+432ldHhEjSciKYtpX8L5OQtX9uNykTuHQQ2IPRiDWg6qPmVsFY/DxpsGvTnSfWEPvJw2qrdZ nabilelkhalii@nabilelkhalii-VirtualBox"
        virtual_network_name: "{{ vnet_name }}"
        subnet_name: "{{ subnet_name }}"
        public_ip_allocation_method: Dynamic
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
      register: output

    - name: add azure vm into host
      add_host:
        name: new_azure_vm
        ansible_host: '{{ output.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'
        ansible_connection: paramiko  # not guaranteed to have sshpass...
        ansible_user: "{{ admin_username }}"
        ansible_password: "{{ admin_password }}"
        ansible_host_key_checking: true

    - name: wait for the WinRM port to come online
      wait_for:
        port: 22
        host: '{{ output.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'
        timeout: 600

    - name: Git Clone
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workspace }}"

    - name: build sample app
      shell: mvn package chdir="{{ workspace }}"

    - block:
      - name: Update repositories cache and install "tomcat8" package
        become: true
        apt:
          name: tomcat8
          update_cache: yes

      - name: Install "tomcat8-admin" package
        become: true
        apt:
          name: tomcat8-admin

      - name: copy app to azure vm
        become: true
        copy:
          src: "{{ workspace }}/target/demo-0.0.1-SNAPSHOT.war"
          dest: /var/lib/tomcat8/webapps/hello.war
          force: yes
          mode: 0755

      - name: Start and enable Tomcat service
        become: true
        systemd:
          name: tomcat8
          state: started
          enabled: true
          daemon_reload: true
      delegate_to: new_azure_vm